### ISSUE TITLE
Generator stops working when minimizing app

### ISSUE THREAD

**Issue by ttseng** [ezefranca/FSK-Arduino-iOS#4]
Thanks a lot for sharing this project – it's the basis of an iOS app I've written for my research project:

http://spin.media.mit.edu/

I have noticed that the audio generation is inconsistent.  Specifically, if someone returns to the homescreen and then re-opens the app, it seems like the audio generation doesn't work.  Do you have any ideas about how to fix this?

**Comment by ezefranca** [comment]
In my example not arrived this situation. In your case, I think the one possible way is check your object in Appdelegate method.

```- (void)applicationDidBecomeActive:(UIApplication *)application ```
if returns nil, you can instantiate it again.

If you show some part of your code, it will be a pleasure to help.

**Comment by ttseng** [comment]
Thanks – this is exactly what I ended up doing!
